---
- hosts: all
  name: Add cis-91 packages
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - python3-pip 
          - python3-venv
          - nginx
          - apache2
          - nodejs
    - name: Create a ext4 filesystem on lab09
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-lab09

    - name: Mount extra disk
      ansible.posix.mount:
        path: /mnt
        src: /dev/disk/by-id/google-lab09
        fstype: ext4
        state: present

    - name: Create a ext4 filesystem for storage1
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-storage1

    - name: Mount up storage1
      ansible.posix.mount:
        path: /mnt/data
        src: /dev/disk/by-id/google-storage1
        fstype: ext4
        state: present    

    - name: Create a ext4 filesystem for storage2
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-storage2

    - name: Mount up storage2
      ansible.posix.mount:
        path: /mnt/scratch
        src: /dev/disk/by-id/google-storage2
        fstype: ext4
        state: present    